server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://luxury-shop-db.c5zpkudkm642.ap-northeast-2.rds.amazonaws.com/luxury-shop
    username: admin
    password: luxuryshop12
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    generate-ddl: true
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE