server:
  port: 8080
spring:

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    #spring:
    #  config:
    #    activate:
  #  on-profile: prod
    # datasource:
    # hikari:
    #  driver-class-name: org.h2.Driver
    #  jdbc-url: jdbc:h2:mem:testdb
    # username: admin
  #password: luxuryshop12
    # jpa:
    #hibernate:
    #  ddl-auto: create-drop
    #properties:
    #  hibernate:
    #    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    #    format_sql: true
    # show-sql: true
      #generate-ddl: true
      #logging:
  #level:
    #org:
      # hibernate:
      #     SQL: DEBUG
    #       type:
    hibernate:
      ddl-auto: create-drop
  #           descriptor:

#              sql:
#                BasicBinder: TRACE